version: "3"
services:
  site:
    command: jekyll serve --future --unpublished --drafts -l
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      GEM_HOME: /usr/local/bundle
      GEM_BIN: /usr/local/bundle/bin
    ports:
      - 4000:4000
      - 35729:35729
    
